// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2_BookingMVCApp.Infrastructure.Data;

#nullable disable

namespace _2_BookingMVCApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_1_BookingMVCApp.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 21, 10, 2, 13, 63, DateTimeKind.Local).AddTicks(904),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum porttitor semper. Fusce arcu justo, venenatis ac hendrerit ac, mollis a nisl. Vestibulum sagittis tellus justo, et hendrerit ligula vulputate eleifend. Duis mollis leo in augue malesuada, et congue purus elementum. Donec rutrum, erat nec pulvinar efficitur, odio sapien suscipit massa, id mattis libero massa rhoncus est. Suspendisse faucibus molestie posuere. Cras ut purus a urna fermentum dapibus. Pellentesque ut nibh mollis, venenatis ex sit amet, volutpat nisl. Maecenas elit tellus, cursus id placerat a, gravida vitae sem. Vestibulum vestibulum, tortor maximus dapibus ultricies, justo ligula tempor magna, eu aliquam sapien nunc vel nunc. Pellentesque a ullamcorper ligula. Cras nec finibus justo, non feugiat justo. Sed at tincidunt massa, a gravida neque. Curabitur ac rutrum mauris.",
                            ImageUrl = "https://via.placeholder.com/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200m,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 21, 10, 2, 13, 63, DateTimeKind.Local).AddTicks(918),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum porttitor semper. Fusce arcu justo, venenatis ac hendrerit ac, mollis a nisl. Vestibulum sagittis tellus justo, et hendrerit ligula vulputate eleifend. Duis mollis leo in augue malesuada, et congue purus elementum. Donec rutrum, erat nec pulvinar efficitur, odio sapien suscipit massa, id mattis libero massa rhoncus est. Suspendisse faucibus molestie posuere. Cras ut purus a urna fermentum dapibus. Pellentesque ut nibh mollis, venenatis ex sit amet, volutpat nisl. Maecenas elit tellus, cursus id placerat a, gravida vitae sem. Vestibulum vestibulum, tortor maximus dapibus ultricies, justo ligula tempor magna, eu aliquam sapien nunc vel nunc. Pellentesque a ullamcorper ligula. Cras nec finibus justo, non feugiat justo. Sed at tincidunt massa, a gravida neque. Curabitur ac rutrum mauris.",
                            ImageUrl = "https://via.placeholder.com/600x400",
                            Name = "Premium Royal Villa",
                            Occupancy = 4,
                            Price = 300m,
                            Sqft = 550
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 21, 10, 2, 13, 63, DateTimeKind.Local).AddTicks(919),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dictum porttitor semper. Fusce arcu justo, venenatis ac hendrerit ac, mollis a nisl. Vestibulum sagittis tellus justo, et hendrerit ligula vulputate eleifend. Duis mollis leo in augue malesuada, et congue purus elementum. Donec rutrum, erat nec pulvinar efficitur, odio sapien suscipit massa, id mattis libero massa rhoncus est. Suspendisse faucibus molestie posuere. Cras ut purus a urna fermentum dapibus. Pellentesque ut nibh mollis, venenatis ex sit amet, volutpat nisl. Maecenas elit tellus, cursus id placerat a, gravida vitae sem. Vestibulum vestibulum, tortor maximus dapibus ultricies, justo ligula tempor magna, eu aliquam sapien nunc vel nunc. Pellentesque a ullamcorper ligula. Cras nec finibus justo, non feugiat justo. Sed at tincidunt massa, a gravida neque. Curabitur ac rutrum mauris.",
                            ImageUrl = "https://via.placeholder.com/600x400",
                            Name = "Luxury Royal Villa",
                            Occupancy = 4,
                            Price = 400m,
                            Sqft = 750
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
